name: Java CI with Maven

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4                     # This step checks out a copy of your repository
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'                          # This step sets up JDK 11 for use with Maven
        cache: 'maven'

    - name: Build with Maven
      run: mvn -B package --file pom.xml            # This step builds the project with Maven

    - name: Provide execution rights to deploy.sh
      run: chmod +x ./deploy.sh

    - name: Deploy
      run: ./deploy.sh
#
#    - name: Run the app
#      run: mvn spring-boot:run                      # This step runs your Spring Boot application.